version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false
python:
  install:
    - sphinx
    - sphinx_rtd_theme 
    - requirements: requirements/docs.txt
formats: []