version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install --upgrade docutils
sphinx:
  configuration: conf.py
python:
  install:
    - requirements: requirements/docs.txt
formats: []