version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - "pip install sphinx"
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false
python:
  install:
    - requirements: requirements/docs.txt
formats: []